export const STORE_PERSONAL_DETAILS = 'STORE_PERSONAL_DETAILS';
export const PERSONAL_DETAILS_RESET = 'PERSONAL_DETAILS_RESET';

export const STORE_PROFESSIONAL_DETAILS = 'STORE_PROFESSIONAL_DETAILS';
export const PROFESSIONAL_DETAILS_RESET = 'PROFESSIONAL_DETAILS_RESET';

export const STORE_DETAILS = 'STORE_DETAILS';